### ISSUE TITLE
`/import` fails

### ISSUE THREAD

**Issue by geordi** [mrlvsb/kelvin#152]
`/import` fails when there's a teacher without diacritics in `Users` but in schedule diacritics is present.

Problem is probably somewhere here [bulk_import.py#L87](https://github.com/mrlvsb/kelvin/blob/master/common/bulk_import.py#L87).

**Comment by geordi** [comment]
OK, we also need a safe way to import users (teachers) with diacritics. So far, if I wanted to create a user (teacher), I added him as a student to a class, which creates a new user __but without diacritics__. Then I remove the user from class and set teacher group in admin.

**Comment by trnila** [comment]
We can create teachers individually in django admin - is it enough?
I think EDISON export has only teacher name, but without login...

**Comment by geordi** [comment]
Will at the INBUS interface and see what's available there.

**Comment by geordi** [comment]
INBUS provides names with diacritics. Also, import of classes can be made from INBUS. This is more broadly discussed in #193.
