### ISSUE TITLE
Add quick buttons for moving to first/last submission of student

### ISSUE THREAD

**Issue by Kobzol** [mrlvsb/kelvin#174]
On the teacher page for displaying student submissions (`/task/<task-id>/<student-login>/<submission-id>/`), there are buttons for moving to the next/previous submission. However, sometimes there are a lot of submissions, so it would be nice to have separate buttons (like `<<` and `>>`) for moving to the first and last submission.

**Comment by trnila** [comment]
We can also go to prev/next comment with left/right arrow. Maybe we can hold shift+arrow to first or last submit
