### ISSUE TITLE
Fix overlap of submission comments and quick buttons

### ISSUE THREAD

**Issue by Kobzol** [mrlvsb/kelvin#175]
On the teacher page that displays user submissions, comments can overlap with quick buttons on the right:
![image](https://user-images.githubusercontent.com/4539057/157611282-a1138de3-fb77-4d4b-85cc-0c58875eb039.png)

**Comment by geordi** [comment]
Looks like it does something different.

**Comment by tomasmensik** [comment]
Before: https://ctrlv.link/M7AM
After: https://ctrlv.link/12cQ
