### ISSUE TITLE
Simple markup in code comments

### ISSUE THREAD

**Issue by geordi** [mrlvsb/kelvin#35]
Add support for a simple markup for `code` strings in comments:

Changes need to mage in:

https://github.com/mrlvsb/kelvin/blob/master/web/static/comments.vue#L41
https://github.com/mrlvsb/kelvin/blob/master/web/views/student.py#L256

And use:
https://vuejs.org/v2/guide/computed.html

**Comment by Kobzol** [comment]
Markdown can now be used in comments.
Fixed by #65
