### ISSUE TITLE
Points statistics not correct

### ISSUE THREAD

**Issue by geordi** [mrlvsb/kelvin#379]
I thing, point stats is not displaying correct data, see screenshot below:

![points_stats](https://github.com/mrlvsb/kelvin/assets/263425/a1ed99e8-e216-460f-87b1-e125c311d0ff)

**Comment by Kobzol** [comment]
Send a link/name of the AssignedTask or filter for homepage, how to find it.

**Comment by geordi** [comment]
It behaves the same for every class with any assigned task. It counts number of students with any submit over number of students.

**Comment by Kobzol** [comment]
It seems to work fine here: https://kelvin.cs.vsb.cz/#/?semester=2023W&subject=KPZD.

**Comment by Kobzol** [comment]
Oh, I see, the problem is with non-graded submits, I guess that they are assumed to be zero at the moment.
