### ISSUE TITLE
Notifications are not scrollable

### ISSUE THREAD

**Issue by DavidHusicka** [mrlvsb/kelvin#455]
When student has too many notifications, to scroll in them, they have to scroll the entire site site. The notification box should be scrollable itself.

![image](https://github.com/mrlvsb/kelvin/assets/25853767/c5367dae-2e98-475c-b0bb-f5c2814cb729)
![image](https://github.com/mrlvsb/kelvin/assets/25853767/98ef71d2-a7fd-4112-b415-e2ff3c90665d)

**Comment by geordi** [comment]
Thank you for noticing. We're definitely aware of it. It would be grade, if you provide a PR with a fix.
