### ISSUE TITLE
Display # of source code comments

### ISSUE THREAD

**Issue by geordi** [mrlvsb/kelvin#52]
Display # of source code comments provided by teacher in teacher's view. Can be next to assigned points in a bracket.

**Comment by Kobzol** [comment]
This PR added it to the `Source code` tab: https://github.com/mrlvsb/kelvin/pull/69. You also want it on the main teacher UI, right?

**Comment by geordi** [comment]
Yea, I do.

**Comment by Kobzol** [comment]
It would also be nice to display # of comments per file for submits with multiple files.

**Comment by Kobzol** [comment]
This has been implemented a long time ago.
